import existing state

diff --git a/.github/workflows/test-and-deploy.yml b/.github/workflows/test-and-deploy.yml
--- a/.github/workflows/test-and-deploy.yml
+++ b/.github/workflows/test-and-deploy.yml
@@ -32,6 +32,21 @@ jobs:
         run: |
           bundle install
       - uses: hashicorp/setup-terraform@v2
+
+      - name: Check and Import Existing Lambda
+        run: |
+          LAMBDA_EXISTS=$(aws lambda get-function --function-name RecapHoldRequestConsumer-qa 2>&1 || true)
+          if echo "$LAMBDA_EXISTS" | grep "Lambda not found"; then
+            echo "Lambda does not exist, proceeding with creation"
+          else
+            echo "Lambda exists, importing into Terraform state"
+            terraform -chdir=provisioning/qa import aws_lambda_function.lambda_instance arn:aws:lambda:us-east-1:946183545209:function:RecapHoldRequestConsumer-qa
+          fi
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: 'us-east-1'
+
       - name: Deploy app to QA
         run: |
           terraform -chdir=provisioning/qa init -input=false
